name: eeg_encoding
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
- python
- numpy
- pandas
- scipy
- scikit-learn
- matplotlib
- pytorch
- torchvision
- tqdm
- pip
- pip:
  - mne
  - argparse
  - cornet
